server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/muvautomation;
    index index.html;
    server_name _;

    server_tokens off;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;
    autoindex off;

    location ~ /\. { deny all; }
    location / { try_files $uri $uri/ =404; }
}
